import type { Metadata } from 'next';
import { DefaultTemplate } from '~templates';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <DefaultTemplate>{children}</DefaultTemplate>
    </html>
  );
}
